### ISSUE TITLE
Did not recognizance contenttype

### ISSUE THREAD

**Issue by killje** [o5/apib2json#1]
I tried using this tool to convert our blueprint to json and got a empty object as output.

After some debugging found out that line 93 of lib/apib2json.js was the problem.

It checks the content type for "application/scheme+json" While for the blueprint we use it was "application/json".

A possible solution for this is to check for both or make a  regex expression to catch multiple cases (i have personally never seen scheme+json so there might be a few others i have never seen).

(For the rest this tool was exactly what i was looking for. No other npm module could give me something to mock requests that where defined in apib)

**Comment by o5** [comment]
Hi @killje,

content type `application/scheme+json` is provided by Protagonist parser and [there](https://tools.ietf.org/html/draft-wright-json-schema-01) is a draft for this content-type. You can look at Blueprint in [fixtures folder](https://github.com/o5/apib2json/blob/master/test/fixtures/advanced_attributes_api.apib.md), there is only `application/json` used. 

I can't do more without your Blueprint.

Best

**Comment by o5** [comment]
Closing, no response.
