### ISSUE TITLE
Missing atrribute in schema

### ISSUE THREAD

**Issue by starek4** [o5/apib2json#6]
Hi,

I have problem with parsing attributes and I do not know if I missing something or if this is a bug.

I will try to demonstrate it on following minimal example. This is the minimal blueprint file:
```
FORMAT: 1A

# Minimal example API

Example of minimal API

# Group Authentication

## Authentication [/et/v1/{id}/auth]
Authentication...

+ Parameters
    + id: `42` (number) - example id

### Initialize Authentication [GET]

+ Response 200 (application/json)
    + Attributes (AuthenticationModel)

# Data Structures

## BaseModel (object)
+ _links (string)

## AuthenticationModel (BaseModel)
+ example (boolean)
```

And this is corresponding json output, generated using apib2json.
```
{
  "[GET]/et/v1/{id}/auth": [
    {
      "meta": {
        "type": "response",
        "title": null,
        "group": "Authentication",
        "statusCode": "200"
      },
      "schema": {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type": "object",
        "properties": {
          "_links": {
            "type": "string"
          },
          "example": {
            "type": "boolean"
          }
        }
      }
    }
  ]
}
```

Unfortunately, I cannot find any information about `id` parameter in generated JSON file. Am I missing something or is it a bug?

**Comment by o5** [comment]
Hello @starek4, you defined `id` as GET parameter so this parameter cannot be in JSON Schema (which is primally for request / response **body**). 

This is not a behaviour of apib2json but Apiary's protagonist. If you need to validate this parameter, use for example POST method.
